export const WEATHER_API = [
  { id: 1, city: 'London', temp: 15 },
  {id: 2, city: 'Paris', temp: 18 },
  { id: 3,city: 'Berlin', temp: 12 },
  { id: 4,city: 'Madrid', temp: 24 },
  { id: 5,city: 'Rome', temp: 21 },
  { id: 6,city: 'Amsterdam', temp: 13 },
  { id: 7,city: 'Vienna', temp: 14 },
  { id: 8, city: 'Prague', temp: 11 },
  { id: 9,city: 'Warsaw', temp: 10 },
  { id: 10,city: 'Budapest', temp: 16 },
  { id: 11,city: 'Lisbon', temp: 22 },
  { id: 12,city: 'Athens', temp: 27 },
  { id: 13,city: 'Stockholm', temp: 8 },
  { id: 14,city: 'Oslo', temp: 6 },
  { id: 15,city: 'Helsinki', temp: 5 },
];
